### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by zootedb0t** [zootedb0t/url_shortner#34]
- [x]  Add option to delete api keys from database
- [x]  Add check for empty api key
- [x]  Center api table
